import type { Metadata } from "next";
import { Poppins, Koulen } from "next/font/google";
import "./globals.css";
import Footer from "@/components/landing-page/Footer";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const koulen = Koulen({
  subsets: ["latin"],
  variable: "--font-koulen",
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${koulen.variable} antialiased bg-black`}
      >
        <div>
          {children}
          <Footer/>
        </div>
        <Toaster/>
      </body>
    </html>
  );
}
