import type { Metadata } from "next";
import { Poppins, Koulen, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const koulen = Koulen({
  subsets: ["latin"],
  variable: "--font-koulen",
  weight: ["400"],
});

const playFair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "HackAttack 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${playFair.variable} ${koulen.variable} antialiased font-poppins `}
      >
        <div>
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
