import type { Metadata } from "next";
import { Poppins, Koulen } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";

// import Navbar from "@/components/coming-soon/Navbar";
// import Footer from "@/components/coming-soon/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const koulen = Koulen({
  subsets: ["latin"],
  variable: "--font-koulen",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "HackAttack 2025",
  description: "Generated by create next app",
  metadataBase: new URL("https://hackattack2025.com"),
  other: {
    link: [
      "preconnect=https://fonts.googleapis.com",
      "preconnect=https://fonts.gstatic.com",
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${koulen.variable} font-poppins antialiased bg-[#0C0E13]`}
      >
        {/* <Navbar/> */}
        <main>{children}</main>
        <Toaster />
        <SpeedInsights />
        {/* <Footer/> */}
      </body>
    </html>
  );
}
